name: Build

on:
  pull_request:
  push:
    branches:
      - '**'
      - '!main'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v3
        with:
          build-args: --progress plain
          platforms: linux/amd64, linux/arm64
